DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS event;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE event (
  event_id INTEGER PRIMARY KEY AUTOINCREMENT,
  category TEXT NOT NULL,
  date DATE NOT NULL,
  location TEXT NOT NULL,
  time TIME NOT NULL,
  venue TEXT NOT NULL
);
